name: Scrape Letterboxd

on:
  push:
    branches: [main]
  schedule:
    - cron: '*/2 * * * *'  # Every 10 minutes
  workflow_dispatch:

concurrency:
  group: scrape
  cancel-in-progress: false

jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scraper
      run: python scraper.py

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git add -A docs/
        git commit -m "Update docs" || true
        git push origin main:gh-pages
